config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'post/index'
  get 'pages/home'
  root "pages#home"
  get "pages/about_us", to: "pages#about_us"
  get "pages/contact"
  get "post/index", to: "post#hello", as:"post"
  get "hello/:name", to: "pages#hello", as:"hello"

  # get "/products", to: "products#index"
  # get "/products/new", to: "products#new", as: "new_product"
  # post  "/products", to: "products#create"
  # get "/products/:id", to: "products#show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :users
  has many :comments, as: :comentable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :comentable
  # validates :title, :body, presence: true
  # validates :published, inclusion: { in: [true,false]}
scope :published, -> { where(published: true)} #igual a otra lineas abajo
scope :created_before, -> (time) { where("created_at < ?", time)}
end

#Exctamente lo mismo de la linea 6
# def self.published
#   where(published: true)
# end

#n la conosla
#Post.first(3).each { |post| post.update_column(:published, false)}  #coge los 3 primeros post y los pasa a falso

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_and_belongs_to_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
# layout "mi_layout", only: [:hello] #Pasar atributos y cambiar layout de paginas,
#about_us ruta , metodo y vista q se llame igual al metodo

def about_us
  @greeting = "Lorem ipsum dolor"
end

def hello
    @name = params[:name]
end

#contact   direccion y telefono ,
def contact
  @contact = ["Zorro arango", 3504500059]
end

#posts array de strings
# def posts
#   @posts = Post.all
# end

end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.all
  end
end
# gernerar conotrolador de post, dentro metodo index a ese arroba post y crear la ruta

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
   @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(params[:product_params])
    if @product.save
      redirect_to_products_path
    else
      render :new
    end
  end
  def edit
  @product = Product.find(params[:id])
   end
   def update
     @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to products_path
      else
        render :edit
      end
   end
   def destroy
     product = Product.find(params[:id])
     product.destroy
     redirect_to products_path
   end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <a href="<%= pages_about_us_path %>">Sobre nosotros</a>
    <a href="<%= pages_contact_path %>">Contacto</a>
    <a href="<%= post_path %>">Posts</a>
    <ul>
      <li><%= link_to "hello", hello_path("Christian") %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Hi <%= @greeting %></h1>

<p>Find me in app/views/pages/about_us.html.erb</p>

app/views/pages/contact.html.erb
<h1> <%= @contact %></h1>

<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/hello.html.erb
<h1>Welcome <%= @name %></h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<a href<"<%= pages_home_path %>"> home</a>

app/views/pages/posts.html.erb
<p>Find me in app/views/pages/posts.html.erb</p>

<ul>
  <% @posts.each do |post| %>
  <li><%= post.title %> - <%= post.body%></li>
  <% end %>
</ul>

app/views/post/index.html.erb
<h1>Index</h1>

app/views/products/_form.html.erb
<h1><%= action %> Product </h1>

<%= form_for @product do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
   <div>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render "form",product: @product,action: "Edit" %>

app/views/products/index.html.erb
<h1>Productos</h1>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Precio</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <%= link_to "Mostrar", product %>
          <%= link_to "Editar", edit_product_path(product) %>
          <%= link_to "Eliminar", product, method: :delete, data: { confirm: "¿Estás seguro de eliminar este producto?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%= render "form", product: @product, action: "New" %>

app/views/products/show.html.erb
<h1>Detalles del Producto</h1>
<div>Nombre: <%= @product.name %></div>
<div>Descripción: <%= @product.description %></div>
<div>Precio: <%= @product.price %></div>